### ISSUE TITLE
bug: Madara explorer can't connect to local devnet

### ISSUE THREAD

**Issue by edisontim** [lambdaclass/starknet_stack#105]
After running ```make run-local``` I get the following crash report from the madara explorer container: 

```10:39:05.120 [info] Running StarknetExplorerWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
10:39:05.125 [info] Access StarknetExplorerWeb.Endpoint at https://localhost
10:39:05.128 [info] Warming cache for mainnet
10:39:05.145 [notice] Application starknet_explorer exited: StarknetExplorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: :mainnet_block_cache
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Cachex.Services.Incubator, {:shutdown, {:failed_to_start_child, StarknetExplorer.Cache.BlockWarmer, {{:badmatch, {:error, :socket_closed_remotely}}, [{StarknetExplorer.Rpc, :send_request_no_cache, 3, [file: 'lib/starknet_rpc.ex', line: 58]}, {StarknetExplorer.Cache.BlockWarmer, :execute, 1, [file: 'lib/cache_request_warmer.ex', line: 17]}, {StarknetExplorer.Cache.BlockWarmer, :handle_info, 2, [file: 'deps/cachex/lib/cachex/warmer.ex', line: 95]}, {StarknetExplorer.Cache.BlockWarmer, :init, 1, [file: 'deps/cachex/lib/cachex/warmer.ex', line: 79]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 851]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}}}}}
            (cachex 3.6.0) lib/cachex.ex:301: Cachex.start_link/1
            (stdlib 4.3.1.2) supervisor.erl:420: :supervisor.do_start_child_i/3
            (stdlib 4.3.1.2) supervisor.erl:406: :supervisor.do_start_child/2
            (stdlib 4.3.1.2) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 4.3.1.2) supervisor.erl:1256: :supervisor.children_map/4
            (stdlib 4.3.1.2) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 4.3.1.2) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.3.1.2) gen_server.erl:814: :gen_server.init_it/6
{"Kernel pid terminated",application_controller,"{application_start_failure,starknet_explorer,{{shutdown,{failed_to_start_child,mainnet_block_cache,{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,'Elixir.Cachex.Services.Incubator',{shutdown,{failed_to_start_child,'Elixir.StarknetExplorer.Cache.BlockWarmer',{{badmatch,{error,socket_closed_remotely}},[{'Elixir.StarknetExplorer.Rpc',send_request_no_cache,3,[{file,\"lib/starknet_rpc.ex\"},{line,58}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',execute,1,[{file,\"lib/cache_request_warmer.ex\"},{line,17}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',handle_info,2,[{file,\"deps/cachex/lib/cachex/warmer.ex\"},{line,95}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',init,1,[{file,\"deps/cachex/lib/cachex/warmer.ex\"},{line,79}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}}}}}},[{'Elixir.Cachex',start_link,1,[{file,\"lib/cachex.ex\"},{line,301}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,420}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,406}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,390}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1256}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]}]}}}},{'Elixir.StarknetExplorer.Application',start,[normal,[]]}}}"}
10:39:28.033 [info] Running StarknetExplorerWeb.Endpoint with cowboy 2.10.0 at :::4000 (http)
10:39:28.033 [info] Access StarknetExplorerWeb.Endpoint at https://localhost
10:39:28.042 [info] Warming cache for mainnet
10:39:28.063 [notice] Application starknet_explorer exited: StarknetExplorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: :mainnet_block_cache
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, {:shutdown, {:failed_to_start_child, Cachex.Services.Incubator, {:shutdown, {:failed_to_start_child, StarknetExplorer.Cache.BlockWarmer, {{:badmatch, {:error, :econnrefused}}, [{StarknetExplorer.Rpc, :send_request_no_cache, 3, [file: 'lib/starknet_rpc.ex', line: 58]}, {StarknetExplorer.Cache.BlockWarmer, :execute, 1, [file: 'lib/cache_request_warmer.ex', line: 17]}, {StarknetExplorer.Cache.BlockWarmer, :handle_info, 2, [file: 'deps/cachex/lib/cachex/warmer.ex', line: 95]}, {StarknetExplorer.Cache.BlockWarmer, :init, 1, [file: 'deps/cachex/lib/cachex/warmer.ex', line: 79]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 851]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 814]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 240]}]}}}}}}
            (cachex 3.6.0) lib/cachex.ex:301: Cachex.start_link/1
            (stdlib 4.3.1.2) supervisor.erl:420: :supervisor.do_start_child_i/3
            (stdlib 4.3.1.2) supervisor.erl:406: :supervisor.do_start_child/2
            (stdlib 4.3.1.2) supervisor.erl:390: anonymous fn/3 in :supervisor.start_children/2
            (stdlib 4.3.1.2) supervisor.erl:1256: :supervisor.children_map/4
            (stdlib 4.3.1.2) supervisor.erl:350: :supervisor.init_children/2
            (stdlib 4.3.1.2) gen_server.erl:851: :gen_server.init_it/2
            (stdlib 4.3.1.2) gen_server.erl:814: :gen_server.init_it/6
{"Kernel pid terminated",application_controller,"{application_start_failure,starknet_explorer,{{shutdown,{failed_to_start_child,mainnet_block_cache,{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,'Elixir.Cachex.Services.Incubator',{shutdown,{failed_to_start_child,'Elixir.StarknetExplorer.Cache.BlockWarmer',{{badmatch,{error,econnrefused}},[{'Elixir.StarknetExplorer.Rpc',send_request_no_cache,3,[{file,\"lib/starknet_rpc.ex\"},{line,58}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',execute,1,[{file,\"lib/cache_request_warmer.ex\"},{line,17}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',handle_info,2,[{file,\"deps/cachex/lib/cachex/warmer.ex\"},{line,95}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',init,1,[{file,\"deps/cachex/lib/cachex/warmer.ex\"},{line,79}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}}}}}},[{'Elixir.Cachex',start_link,1,[{file,\"lib/cachex.ex\"},{line,301}]},{supervisor,do_start_child_i,3,[{file,\"supervisor.erl\"},{line,420}]},{supervisor,do_start_child,2,[{file,\"supervisor.erl\"},{line,406}]},{supervisor,'-start_children/2-fun-0-',3,[{file,\"supervisor.erl\"},{line,390}]},{supervisor,children_map,4,[{file,\"supervisor.erl\"},{line,1256}]},{supervisor,init_children,2,[{file,\"supervisor.erl\"},{line,350}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,851}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,814}]}]}}}},{'Elixir.StarknetExplorer.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,starknet_explorer,{{shutdown,{failed_to_start_child,mainnet_block_cache,{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,'Elixir.Cachex.Services.Incubator',{shutdown,{failed_to_start_child,'Elixir.StarknetExplorer.Cache.BlockWarmer',{{badmatch,{error,socket_closed_remotely}},[{'Elixir.StarknetExplorer.Rpc',send_request_no_cache,3,[{file,"lib/starknet_rpc.ex"},{line,58}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',execute,1,[{file,"lib/cache_request_warmer.ex"},{line,17}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',handle_info,2,[{file,"deps/cachex/lib/cachex/warmer.ex"},{line,95}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',init,1,[{file,"deps/cachex/lib/cachex/warmer.ex"},{line,79}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,851}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}}},[{'Elixir.Cachex',start_link,1,[{file,"lib/cac

Crash dump is being written to: erl_crash.dump...done
Kernel pid terminated (application_controller) ({application_start_failure,starknet_explorer,{{shutdown,{failed_to_start_child,mainnet_block_cache,{'EXIT',{{badmatch,{error,{shutdown,{failed_to_start_child,'Elixir.Cachex.Services.Incubator',{shutdown,{failed_to_start_child,'Elixir.StarknetExplorer.Cache.BlockWarmer',{{badmatch,{error,econnrefused}},[{'Elixir.StarknetExplorer.Rpc',send_request_no_cache,3,[{file,"lib/starknet_rpc.ex"},{line,58}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',execute,1,[{file,"lib/cache_request_warmer.ex"},{line,17}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',handle_info,2,[{file,"deps/cachex/lib/cachex/warmer.ex"},{line,95}]},{'Elixir.StarknetExplorer.Cache.BlockWarmer',init,1,[{file,"deps/cachex/lib/cachex/warmer.ex"},{line,79}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,851}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,814}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}}},[{'Elixir.Cachex',start_link,1,[{file,"lib/cachex.ex"},{

Crash dump is being written to: erl_crash.dump...done
```

Here's the erl_crash.dump if needed :) 
[erl_crash.txt](https://github.com/lambdaclass/starknet_stack/files/12358429/erl_crash.txt)

**Comment by edisontim** [comment]
```
[2023-08-17T03:44:20.065Z INFO  mempool::config] Garbage collection depth set to 50 rounds
[2023-08-17T03:44:20.065Z INFO  mempool::config] Sync retry delay set to 5000 ms
[2023-08-17T03:44:20.065Z INFO  mempool::config] Sync retry nodes set to 3 nodes
[2023-08-17T03:44:20.065Z INFO  mempool::config] Batch size set to 4096 B
[2023-08-17T03:44:20.065Z INFO  mempool::config] Max batch delay set to 10 ms
[2023-08-17T03:44:20.066Z INFO  mempool::mempool] Mempool listening to client transactions on 0.0.0.0:9004
[2023-08-17T03:44:20.066Z INFO  mempool::mempool] Mempool listening to mempool messages on 0.0.0.0:9008
[2023-08-17T03:44:20.066Z INFO  mempool::mempool] Mempool successfully booted on 172.27.0.10
[2023-08-17T03:44:20.067Z INFO  consensus::config] Timeout delay set to 1000 rounds
[2023-08-17T03:44:20.067Z INFO  consensus::config] Sync retry delay set to 10000 ms
[2023-08-17T03:44:20.068Z INFO  consensus::consensus] Node 25IViUk10zjCqYI6 listening to consensus messages on 0.0.0.0:9000
[2023-08-17T03:44:20.069Z INFO  node::node] Node 25IViUk10zjCqYI6 successfully booted
[2023-08-17T03:44:20.069Z INFO  node::node] RPC Server started, running on port 10008
[2023-08-17T03:44:20.262Z INFO  network::receiver] Incoming connection established with 172.27.0.11:37716
[2023-08-17T03:44:20.263Z INFO  network::receiver] Incoming connection established with 172.27.0.13:58882
thread 'tokio-runtime-worker' panicked at 'Block not found', rpc_endpoint/src/starknet_backend.rs:117:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-08-17T03:44:21.066Z INFO  network::receiver] Incoming connection established with 172.27.0.12:54322
[2023-08-17T03:44:21.067Z INFO  network::receiver] Incoming connection established with 172.27.0.13:58898
[2023-08-17T03:44:21.070Z INFO  network::receiver] Incoming connection established with 172.27.0.11:37718
[2023-08-17T03:44:21.071Z INFO  consensus::proposer] Broadcasting R6FsAw+x9Dyo9Zvo: B(25IViUk10zjCqYI6, 3, QC(miNtI8XydFFhcGwl, 1), 0)
[2023-08-17T03:44:21.071Z INFO  network::reliable_sender] Outgoing connection established with 172.27.0.11:9000
[2023-08-17T03:44:21.071Z INFO  network::reliable_sender] Outgoing connection established with 172.27.0.13:9000
[2023-08-17T03:44:21.076Z INFO  network::reliable_sender] Outgoing connection established with 172.27.0.12:9000
[2023-08-17T03:44:21.076Z INFO  network::receiver] Incoming connection established with 172.27.0.10:33286
[2023-08-17T03:44:21.076Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.10:9000
[2023-08-17T03:44:22.071Z WARN  consensus::core] Timeout reached for round 3
[2023-08-17T03:44:22.071Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.12:9000
[2023-08-17T03:44:22.072Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.13:9000
[2023-08-17T03:44:22.072Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.11:9000
[2023-08-17T03:44:22.072Z INFO  network::receiver] Incoming connection established with 172.27.0.12:54324
[2023-08-17T03:44:22.075Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.11:9000
[2023-08-17T03:44:22.075Z INFO  network::receiver] Incoming connection established with 172.27.0.11:37720
[2023-08-17T03:44:22.076Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.13:9000
[2023-08-17T03:44:22.077Z INFO  consensus::proposer] Broadcasting EdF3NIFoiuGSeOAM: B(25IViUk10zjCqYI6, 7, QC(EWtZ48nVYMhiqnR1, 6), 0)
[2023-08-17T03:44:22.077Z INFO  network::receiver] Incoming connection established with 172.27.0.13:58904
[2023-08-17T03:44:22.078Z INFO  network::simple_sender] Outgoing connection established with 172.27.0.12:9000
[2023-08-17T03:44:22.078Z INFO  network::receiver] Incoming connection established with 172.27.0.12:54332
[2023-08-17T03:44:22.080Z INFO  consensus::proposer] Broadcasting vW9UROpiaCwkVUs6: B(25IViUk10zjCqYI6, 11, QC(XQQOnb4BGl9F8aFs, 10), 0)
[2023-08-17T03:44:22.085Z INFO  consensus::proposer] Broadcasting pi8R2SuhuQS1L6y+: B(25IViUk10zjCqYI6, 15, QC(B9ef8CWSI+J7WZYJ, 14), 0)
[2023-08-17T03:44:22.091Z INFO  consensus::proposer] Broadcasting gqUoR6mKGpjn8TMw: B(25IViUk10zjCqYI6, 19, QC(f6dudPlsOOfxkzkt, 18), 0)
[2023-08-17T03:44:22.098Z INFO  consensus::proposer] Broadcasting SdUt4NbQhC+6HvuR: B(25IViUk10zjCqYI6, 23, QC(9Oh+/nSaex/Kym75, 22), 0)
[2023-08-17T03:44:22.104Z INFO  consensus::proposer] Broadcasting dPBfIVgoXyRxCk/U: B(25IViUk10zjCqYI6, 27, QC(qUjUbTNJNpo8bfFG, 26), 0)
[2023-08-17T03:44:22.108Z INFO  consensus::proposer] Broadcasting RHQO08g64tUbw1hG: B(25IViUk10zjCqYI6, 31, QC(mfz/pODOy2/OVvCg, 30), 0)
[2023-08-17T03:44:22.115Z INFO  consensus::proposer] Broadcasting pqJqOzbaEHOdZ/K7: B(25IViUk10zjCqYI6, 35, QC(Q/hGi/i33WSKKj28, 34), 0)
```
Then it just continues broadcasting blocks

**Comment by igamigo** [comment]
It seems consensus starts correctly but fails to deliver the requested block to the explorer. This is likely because the explorer starts too quickly when no blocks have been committed. If the explorer fails to start, it does not retry. We are working on fixing this. I will have more updates tomorrow.

**Comment by edisontim** [comment]
Trying to reproduce after having pruned my cache of all images and I'm not able to, so it might be a screw-up on my part...

**Comment by edisontim** [comment]
Yeah it's running correctly for me

**Comment by igamigo** [comment]
Closing this as the [explorer was updated](https://github.com/lambdaclass/madara_explorer/commit/2d85e3a0bf89425162fe3d74fbbffaf0dc1ea2bb) to not crash when warming the cache thus avoiding race conditions.
